title: Hardening Apache2
description: This is a grouping of notes that detail how to harden an Apache2 web-server running on a vm hosted Debian12 os.
permalink: /:title/
remote_theme: "dracula/gh-pages"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - full-writeup.md
  - summary.md
